### ISSUE TITLE
How to return text in English?

### ISSUE THREAD

**Issue by gruz** [gierschv/thunderbird-filelink-hubiC#11]
Hi. I use your wonderful extension to attach files, but I get a problem
with wording.

My Thunderbird is in Ukrainian and thus adds text in Ukrainian as well.
See the screenshot:
http://view.xscreenshot.com/d6d6ad17e2c8e24dbf5bad107878246e

Is there any way to make the extension add the text in English (as the
most universal approach)?

As far as I can see the wording is in **cloudAttachmentCountHeader** language constant

Thanks.

**Comment by gierschv** [comment]
Hey there,

Thanks for your question This seems to be hard-coded translation in Thunderbird, so the way to change it will be to use thunderbird in english, or make a custom build:

https://github.com/mozilla/releases-comm-central/blob/07f0552b3f5d8097e8bb97c8271ad28e451d2813/mail/components/compose/content/cloudAttachmentLinkManager.js#L345-L346

Vincent
